name: "Push Build"
on:
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  linux-build-jvm:
    name: Daily - Linux - JVM build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ 11 ]
    steps:
      - uses: actions/checkout@v1
      - uses: actions/cache@v1
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Reclaim Disk Space
        run: .github/ci-prerequisites.sh
      - name: Kubernetes KinD Cluster
        uses: container-tools/kind-action@v1
        with:
          version: v0.11.1
          registry: true
      - name: Install JDK {{ matrix.java }}
        uses: joschi/setup-jdk@e87a7cec853d2dd7066adf837fe12bf0f3d45e52
        with:
          distribution: 'temurin'
          java-version: ${{ matrix.java }}
          check-latest: true
      - name: Generate Samples images
        run: |
          cd samples
          mvn clean install -Dsamples.container-image.registry=$KIND_REGISTRY -Dsamples.container-image.push=true
      - name: Build
        run: |
          mvn -fae -s .github/mvn-settings.xml clean install -Dexamples -Dcoverage -Dvalidate-format \
            -Dsamples.container-image.registry=$KIND_REGISTRY \
            -Dts.container.registry-url=${{ secrets.CI_REGISTRY }} \
            -Dexclude.kubernetes.tests=no
      - name: Generate Jacoco Report
        run: |
          cd coverage-report
          mvn package
      - name: Generate Jacoco Badge
        id: jacoco
        uses: cicirello/jacoco-badge-generator@v2
        with:
          jacoco-csv-file: coverage-report/target/site/jacoco/jacoco.csv
      - name: Coverage Preparation
        id: coverage
        run: |
          echo "coverage = ${{ steps.jacoco.outputs.coverage }}"
          if [[ `git status | grep .svg | wc -l` > 0 ]]; then
            echo ::set-output name=needs-commit-badge::true
          else
            echo ::set-output name=needs-commit-badge::false
          fi
      - name: Commit the badge (if it changed)
        if: steps.coverage.outputs.needs-commit-badge == 'true'
        run: |
          git config --global user.name 'snowdrop'
          git config --global user.email 'snowdrop@users.noreply.github.com'
          git add *.svg
          git commit -m "Autogenerated JaCoCo coverage badge"
      - name: Push the badge (if it changed)
        if: steps.coverage.outputs.needs-commit-badge == 'true'
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          force: true
      - name: Zip Artifacts
        if: failure()
        run: |
          zip -R artifacts-latest-linux-jvm${{ matrix.java }}.zip '*-reports/*'
      - name: Archive artifacts
        if: failure()
        uses: actions/upload-artifact@v1
        with:
          name: ci-artifacts
          path: artifacts-latest-linux-jvm${{ matrix.java }}.zip
      - name: Archive Coverage Report
        uses: actions/upload-artifact@v1
        with:
          name: ci-coverage
          path: coverage-report/target/site/jacoco