name: "Pull Request Build"
on:
  - pull_request
jobs:
  linux-jvm-ocp:
    name: PR - Linux - JVM - OpenShift
    # the action "manusa/actions-setup-openshift@v1.1.4" only works in ubuntu-20.04
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        openshift: [ v3.11.0 ]
        java: [ 8 ]
    steps:
      - uses: actions/checkout@v3
      - name: Reclaim Disk Space
        run: .github/ci-prerequisites.sh
      - name: Configure Registry
        run: |
          mkdir ~/registry
          cd ~/registry
          mkdir data
          docker run -d --restart unless-stopped --network host -e REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY=/data -v $PWD/data:/data registry:2
      - name: Add host
        run: |
          cp /etc/hosts local_hosts
          echo '127.0.0.1 container-registry.org' >> local_hosts
          cat local_hosts
          sudo cp local_hosts /etc/hosts
      - id: add-outputs
        name: Add outputs
        run: |
          echo "CONTAINER_REGISTRY_URL=container-registry.org:5000" >> $GITHUB_ENV
      - name: Install JDK {{ matrix.java }}
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '11'
      - name: Generate Images
        run: |
          cd images
          mvn -s ../.github/mvn-settings.xml clean install -Dsamples.container-image.registry=$CONTAINER_REGISTRY_URL -Dsamples.container-image.push=true