name: "Pull Request Build"
on:
  - pull_request
jobs:
  linux-jvm-ocp:
    name: PR - Linux - JVM - OpenShift
    # the action "manusa/actions-setup-openshift@v1.1.4" only works in ubuntu-20.04
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        openshift: [ v3.11.0 ]
        java: [ 8 ]
    steps:
      - uses: actions/checkout@v3
      - name: Reclaim Disk Space
        run: .github/ci-prerequisites.sh
      - name: Kubernetes KinD Cluster
        uses: container-tools/kind-action@v2
        with:
          version: v0.11.1
          registry: true
      - name: Setup OpenShift
        uses: manusa/actions-setup-openshift@v1.1.4
        with:
          oc version: ${{ matrix.openshift }}
          dns ip: 1.1.1.1
      - name: Install JDK {{ matrix.java }}
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '11'
      - name: Generate Images
        run: |
          cd images
          mvn -s ../.github/mvn-settings.xml clean install -Dsamples.container-image.registry=$KIND_REGISTRY -Dsamples.container-image.push=true
      - name: Build
        run: |
          mvn -s .github/mvn-settings.xml clean install -Pframework -Dexamples -Dcoverage \
            -Denvironment.ci=true \
            -Dsamples.container-image.registry=$KIND_REGISTRY \
            -Dts.services.all.image.registry=$KIND_REGISTRY \
            -Dexclude.openshift.tests=no